### ISSUE TITLE
Create initial user endpoint API reference

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#2]
The [User Endpoint API Reference](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/User-Endpoint-API-Reference) page in the wiki needs to be created. The important parts that need to filled in are the tables containing **Method, Endpoint, Verb, Description**   
However, **Request** and **Response** JSON objects should be discussed here so that we may determine what should be in them.

The use cases the methods need to handle are:
- Create User
- Modify Self (User modifying themselves)
- Modify User (Admin modifying user)
- Delete User
- Get Users

Database schemas needed for this:
- [User](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/Database-Schema-Reference#user)

Do **not** worry about permissions just yet.
**Note:** The table should be oriented around methods. Multiple rows (methods) in the table can have the same Endpoint.

**Comment by ryanfaulkenberry100** [comment]
Assuming admins and mentors are considered users, I think the JSON fields we need are:
**uid**, **username**, **type** (user, admin, etc), and **points**. Anything I'm missing?

**Comment by asclines** [comment]
@ryanfaulkenberry100 Good question, I went ahead and update the issue description here to link to the database objects needed to be edited. You can find all the information needed there

**Comment by ryanfaulkenberry100** [comment]
Since every key in the **admin** object is also a key in the **user** object, I think we should consider just using the **user** object and adding a "userType" key to determine if the user is an admin. If the user is an admin, the user fields that aren't relevant could just be null values

**Comment by asclines** [comment]
@ryanfaulkenberry100 Everybody is a `user`. A `user` is split into two subsections, `admin` and `student`. Does that help?

**Comment by ryanfaulkenberry100** [comment]
@asclines gotcha, thanks.

**Comment by the-pat** [comment]
@ryanfaulkenberry100, after looking through your wiki page I have a few suggestions.

##### [`CreateUser`](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/User-Endpoint-API-Reference#createuser):
  Most of the APIs I have seen do not use verbs in their endpoints. The equivalent endpoint without the verb is: `/user`.

##### [`DeleteUser`](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/User-Endpoint-API-Reference#deleteuser) & [`GetUser`](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/User-Endpoint-API-Reference#deleteuser):
  Since we already have the `uid` from the endpoint (`/user/1234`), we don't need to send the `uid` in the request body.

##### Final Thoughts:
  It does look good. You are really picking this up quickly. Keep up the good work!

**Comment by ryanfaulkenberry100** [comment]
@the-pat thanks for the suggestions, I'll update it!

**Comment by asclines** [comment]
@ryanfaulkenberry100 The wiki seems to be going in the right direction but I have a couple suggestions/comments. 

### `CreateUser`
- Endpoint in long description doesn't match the endpoint in the overview table
- The response doesn't need a URL, just the UID of the newly created user

### `ModifySelf` & `ModifyUser`
- This is just a thought from me but I think we can merge those two methods into one method that just has an additional request parameter that containers the requester's UID so we can check if they have permission.
- Their responses probably only need a HTTP status code

### `DeleteUser`
- Response doesn't need a URL

### `GetUser`
- The response could have a student _or_ a admin object. Instead of just copying the user objects from the [Database Reference Scheme](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/Database-Schema-Reference#users) you could just link it like I just did.

**Comment by ryanfaulkenberry100** [comment]
@asclines I think combining the modify methods is a good idea.

I implemented everything you suggested except linking the database reference, because:
1. The user objects are already copied (read: I'm lazy)
2. Keeping the objects, rather than linking the DRS, makes this wiki a convenient one-page reference

Thanks for the suggestions!

**Comment by asclines** [comment]
Good point @ryanfaulkenberry100   If the user objects update, we will add the link then.
The second point, not the you're lazy point. Lazy people don't show up for Saturday meetings.

**Comment by asclines** [comment]
Closed in #17
