### ISSUE TITLE
Create initial report endpoint API reference

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#4]
The [Report Endpoint API Reference](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/Report-Endpoint-API-Reference) page in the wiki needs to be created. The important parts that need to filled in are the tables containing **Method, Endpoint, Verb, Description**   
However, **Request** and **Response** JSON objects should be discussed here so that we may determine what should be in them.

The use cases the methods need to handle are:
- Create Report
- Modify Report
- Delete Report
- Get Reports

Database schemas needed for this:
- [Report](https://github.com/TTUSDC/CPCEEDWebAppBackend/wiki/Database-Schema-Reference#reports)

Do **not** worry about permissions just yet.
**Note:** The table should be oriented around methods. Multiple rows (methods) in the table can have the same Endpoint.

**Comment by jmtaber129** [comment]
Here's what I'm thinking for request/response objects:

For CreateReport, it seems like all request objects would include Type, Student UID, and Verification.  Event Reports would have an Event UID, and other reports would include Category, Date/Time, Location, Title, and Description.  The response object would probably be status code 201 with the report's UID in the Location header.

Would there be any use case in which it would be desirable to set the report approval status to approved when it's created (e.g. if an admin wanted to create and approve a report on behalf of a student)?  In that case, the request object might also include approval status.

The ModifyReport method's request object would probably include any fields in the CreateReport request object, plus approval status.  The response would probably be status code 200 or 204.  Would we want to return any data related to the modified report?

The DeleteReport method would have no request object (only the UID in the URI).  The response would probably be status code 200, 202, or 204, depending on the status of the operation.  Would we want to return any data related to the deleted report?

The GetReportById method would have no request object (only the UID in the URI).  The response would be status code 200 with all populated fields in the [Reports object](https://github.com/TTUSDC/CPCEEDWebApp/wiki/Database-Objects#reports) referenced by the UID (except the UID itself).

The GetReports method's request object would probably include any fields in the Reports object we might want to search by (probably all but Verification and Description), except UID (which could be obtained through GetReportById).  Search by title might be too much to implement for MVP, since we'd need to find all reports with titles similar to that parameter (rather than the exact title) to be effective (I haven't done much with databases, so this might be a lot easier than I think it is).  The response object would probably be status code 200 with a list of all reports matching the search parameters.

The responses for the GET methods might also include the number of points associated with each report.

Of course, all suggested responses assume happy cases.

**Comment by asclines** [comment]
@jmtaber129 
1. Don't worry about verification just yet. See [here](https://github.com/TTUSDC/CPCEEDWebApp/issues/32) for the discussion were we determined it was not MVP.
2. I do not believe there is _enough_ of a use case for admin creating and approving a report in the same action. At the very least, I do not believe it is MVP. I'm open to debating that point, but I do think that for now, the reports can just be created and then the admin can approve in a second action.
3. In regards to returning data from `ModifyReport`, we could return the updated object? Or a success code.
4. For any sort of deleting, a success code should be sufficient.
5. The `GetReportById` method as you have said it makes sense.
6. For `GetReports` let's not worry too much on searching yet, that's a later problem
7. Happy cases is all we need to worry about for this first iteration. Once we start developing all of this, we will add additional cases such as input errors and malicious users then.

**Comment by jmtaber129** [comment]
I updated the wiki page with the objects, and removed the GetReports method for now.  Let me know if I missed anything or if I should change anything.

**Comment by asclines** [comment]
Looks good, I'm going to mark this as done!
