### ISSUE TITLE
Router design

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#6]
We will be using [Express Routing](https://expressjs.com/en/guide/routing.html) to match endpoints with the right methods. How best to implement routing still needs to be determined.

**Comment by asclines** [comment]
One thing discussed at the meeting on (2/7) is whether it would be better to have a single router file that handled _all_ routing, or an additional layer of routing files.   
With the additional layer, we could have the top layer (the head routing file) handle all initial stages of routing including authentication. Then it could pass the logic on to one of three additional files (EventRouter, ReportRouter, UserRouter) to continue handling the router. 

My concerns is the second way might be overkill. I also don't know how hard it would be to do, or what overheard that it would bring. 

@the-pat If you could look more into this that would be awesome!

**Comment by the-pat** [comment]
After looking over the documentation, Express makes routing very simple. Once we have the endpoints nailed down, basic routing stuff is fairly simple. I like the second way better because it separates the responsibilities of the router by their domain and prevents the files from becoming unmanageable.

I have created a [`router`](https://github.com/TTUSDC/CPCEEDWebAppBackend/tree/router) branch for this issue.

**Comment by asclines** [comment]
@the-pat In addition to what you said, feature based organization also makes sense to me since that is our we are splitting up this project amongst devs.

**Comment by asclines** [comment]
@the-pat is this issue completed?

**Comment by the-pat** [comment]
This issue is complete.
