### ISSUE TITLE
Database Decision

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebAppBackend#7]
Okay so after additional research, I think we should reevaluate our Firebase database decision. 
So a limitation of the way Firebase is setup is that retrieving data using multiple conditions, is inefficient at best. When it comes to [Firebase queries](https://firebase.google.com/docs/reference/js/firebase.database.Query), we can only query on one key. That means we can get all the pending reports **or** all the reports by user, but **not** both. [This S.O. question](http://stackoverflow.com/questions/40419871/how-to-query-by-multiple-keys-in-firebase-database-list) goes into more details if you are interested. 

Another popular database is [MongoDB](https://www.mongodb.com/). MongoDB does allow multiple conditions using a [and](https://docs.mongodb.com/manual/reference/operator/query/and/) operator. 

So what are your thoughts? If we are changing what database we are using, the sooner we make the decision the better.

**Comment by jmtaber129** [comment]
How much slower would it actually be?  Correct me if I'm wrong, but I feel like running a query on a single key, then doing additional filtering on the node server for additional keys (e.g. getting all pending reports, then filtering those results for a specific user) wouldn't be *that* much slower.

**Comment by NilsG-S** [comment]
MongoDB seems like a good option. It would allow us to keep the flexibility of a NoSQL database, while avoiding their inefficiencies on large collections of documents (objects). MongoDB has [indexes](https://docs.mongodb.com/manual/indexes/) and [compound indexes](https://docs.mongodb.com/manual/core/index-compound/#index-type-compound) that would allow us to perform efficient queries on individual and multiple keys respectively.

Being able to perform efficient queries on multiple keys would allow us to simplify our database. Take Alex's example of getting all the pending reports for a specific user. If we wanted to do something like this in firebase efficiently, we would have to keep track of submitted reports in the user object. We could then query from those reports based on approval status. To my knowledge, MongoDB indexes are created using one line of code: `db.collection.createIndex( <key and index type specification>, <options> )`. Since they are pre-existing and presumably quite robust, indexes will probably be better than any system we can come up with on our own.

**Comment by NilsG-S** [comment]
@jmtaber129 My concern is that since the EOC doesn't want to delete old reports, we will eventually reach a point where it will be noticeably inefficient.

**Comment by jmtaber129** [comment]
In that case, MongoDB sounds like the way to go.

**Comment by zachlefevre** [comment]
I'm comfortable with using mongoDB, I'm just curious as to how we'll do authentication without firebase

**Comment by asclines** [comment]
I believe @the-pat has expressed interest in working on that.
@zachlefevre Its doable to say the least.

**Comment by asclines** [comment]
It has been decided 📦
